[project]
name = "lab2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.17.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
    "syncpg>=1.1.3",
]
